//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.12 at 08:59:07 AM IST 
//


package com.zabetan.behpardakht.ipg.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Beneficiary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Beneficiary"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BankDetails" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}AccountAndAddress" minOccurs="0"/&gt;
 *         &lt;element name="BeneficiaryBankDetails" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}AccountAndAddress" minOccurs="0"/&gt;
 *         &lt;element name="ClientInquiryInformation" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}AccountAndAddress" minOccurs="0"/&gt;
 *         &lt;element name="FurtherCreditTo" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}AccountAndAddress" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Beneficiary", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", propOrder = {
    "bankDetails",
    "beneficiaryBankDetails",
    "clientInquiryInformation",
    "furtherCreditTo"
})
public class Beneficiary {

    @XmlElementRef(name = "BankDetails", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<AccountAndAddress> bankDetails;
    @XmlElementRef(name = "BeneficiaryBankDetails", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<AccountAndAddress> beneficiaryBankDetails;
    @XmlElementRef(name = "ClientInquiryInformation", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<AccountAndAddress> clientInquiryInformation;
    @XmlElementRef(name = "FurtherCreditTo", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<AccountAndAddress> furtherCreditTo;

    /**
     * Gets the value of the bankDetails property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public JAXBElement<AccountAndAddress> getBankDetails() {
        return bankDetails;
    }

    /**
     * Sets the value of the bankDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public void setBankDetails(JAXBElement<AccountAndAddress> value) {
        this.bankDetails = value;
    }

    /**
     * Gets the value of the beneficiaryBankDetails property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public JAXBElement<AccountAndAddress> getBeneficiaryBankDetails() {
        return beneficiaryBankDetails;
    }

    /**
     * Sets the value of the beneficiaryBankDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public void setBeneficiaryBankDetails(JAXBElement<AccountAndAddress> value) {
        this.beneficiaryBankDetails = value;
    }

    /**
     * Gets the value of the clientInquiryInformation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public JAXBElement<AccountAndAddress> getClientInquiryInformation() {
        return clientInquiryInformation;
    }

    /**
     * Sets the value of the clientInquiryInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public void setClientInquiryInformation(JAXBElement<AccountAndAddress> value) {
        this.clientInquiryInformation = value;
    }

    /**
     * Gets the value of the furtherCreditTo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public JAXBElement<AccountAndAddress> getFurtherCreditTo() {
        return furtherCreditTo;
    }

    /**
     * Sets the value of the furtherCreditTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public void setFurtherCreditTo(JAXBElement<AccountAndAddress> value) {
        this.furtherCreditTo = value;
    }

}
