//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.12 at 08:59:07 AM IST 
//


package com.zabetan.behpardakht.ipg.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Disbursement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Disbursement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountInfo" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}AccountInfo" minOccurs="0"/&gt;
 *         &lt;element name="Ach" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}AchInstruction" minOccurs="0"/&gt;
 *         &lt;element name="AlternateAddress" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}AccountAndAddress" minOccurs="0"/&gt;
 *         &lt;element name="Beneficiary" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}Beneficiary" minOccurs="0"/&gt;
 *         &lt;element name="DisbursementType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FedRefNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Ira" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}Ira" minOccurs="0"/&gt;
 *         &lt;element name="MailToAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReasonForThirdPartyOrAlternateAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReceiptRefID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReceiverBIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RequestType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SpecialInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ThirdPartyAddress" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}AccountAndAddress" minOccurs="0"/&gt;
 *         &lt;element name="TransactionDetails" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}TransactionDetails" minOccurs="0"/&gt;
 *         &lt;element name="WireReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Disbursement", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", propOrder = {
    "accountInfo",
    "ach",
    "alternateAddress",
    "beneficiary",
    "disbursementType",
    "fedRefNo",
    "ira",
    "mailToAddress",
    "reasonForThirdPartyOrAlternateAddress",
    "receiptRefID",
    "receiverBIC",
    "referenceNumber",
    "requestType",
    "specialInstructions",
    "thirdPartyAddress",
    "transactionDetails",
    "wireReference"
})
public class Disbursement {

    @XmlElementRef(name = "AccountInfo", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<AccountInfo> accountInfo;
    @XmlElementRef(name = "Ach", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<AchInstruction> ach;
    @XmlElementRef(name = "AlternateAddress", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<AccountAndAddress> alternateAddress;
    @XmlElementRef(name = "Beneficiary", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<Beneficiary> beneficiary;
    @XmlElementRef(name = "DisbursementType", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> disbursementType;
    @XmlElementRef(name = "FedRefNo", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fedRefNo;
    @XmlElementRef(name = "Ira", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<Ira> ira;
    @XmlElementRef(name = "MailToAddress", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> mailToAddress;
    @XmlElementRef(name = "ReasonForThirdPartyOrAlternateAddress", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> reasonForThirdPartyOrAlternateAddress;
    @XmlElementRef(name = "ReceiptRefID", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> receiptRefID;
    @XmlElementRef(name = "ReceiverBIC", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> receiverBIC;
    @XmlElementRef(name = "ReferenceNumber", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> referenceNumber;
    @XmlElementRef(name = "RequestType", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> requestType;
    @XmlElementRef(name = "SpecialInstructions", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> specialInstructions;
    @XmlElementRef(name = "ThirdPartyAddress", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<AccountAndAddress> thirdPartyAddress;
    @XmlElementRef(name = "TransactionDetails", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<TransactionDetails> transactionDetails;
    @XmlElementRef(name = "WireReference", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> wireReference;

    /**
     * Gets the value of the accountInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AccountInfo }{@code >}
     *     
     */
    public JAXBElement<AccountInfo> getAccountInfo() {
        return accountInfo;
    }

    /**
     * Sets the value of the accountInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AccountInfo }{@code >}
     *     
     */
    public void setAccountInfo(JAXBElement<AccountInfo> value) {
        this.accountInfo = value;
    }

    /**
     * Gets the value of the ach property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AchInstruction }{@code >}
     *     
     */
    public JAXBElement<AchInstruction> getAch() {
        return ach;
    }

    /**
     * Sets the value of the ach property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AchInstruction }{@code >}
     *     
     */
    public void setAch(JAXBElement<AchInstruction> value) {
        this.ach = value;
    }

    /**
     * Gets the value of the alternateAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public JAXBElement<AccountAndAddress> getAlternateAddress() {
        return alternateAddress;
    }

    /**
     * Sets the value of the alternateAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public void setAlternateAddress(JAXBElement<AccountAndAddress> value) {
        this.alternateAddress = value;
    }

    /**
     * Gets the value of the beneficiary property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Beneficiary }{@code >}
     *     
     */
    public JAXBElement<Beneficiary> getBeneficiary() {
        return beneficiary;
    }

    /**
     * Sets the value of the beneficiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Beneficiary }{@code >}
     *     
     */
    public void setBeneficiary(JAXBElement<Beneficiary> value) {
        this.beneficiary = value;
    }

    /**
     * Gets the value of the disbursementType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDisbursementType() {
        return disbursementType;
    }

    /**
     * Sets the value of the disbursementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDisbursementType(JAXBElement<String> value) {
        this.disbursementType = value;
    }

    /**
     * Gets the value of the fedRefNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFedRefNo() {
        return fedRefNo;
    }

    /**
     * Sets the value of the fedRefNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFedRefNo(JAXBElement<String> value) {
        this.fedRefNo = value;
    }

    /**
     * Gets the value of the ira property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Ira }{@code >}
     *     
     */
    public JAXBElement<Ira> getIra() {
        return ira;
    }

    /**
     * Sets the value of the ira property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Ira }{@code >}
     *     
     */
    public void setIra(JAXBElement<Ira> value) {
        this.ira = value;
    }

    /**
     * Gets the value of the mailToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMailToAddress() {
        return mailToAddress;
    }

    /**
     * Sets the value of the mailToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMailToAddress(JAXBElement<String> value) {
        this.mailToAddress = value;
    }

    /**
     * Gets the value of the reasonForThirdPartyOrAlternateAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReasonForThirdPartyOrAlternateAddress() {
        return reasonForThirdPartyOrAlternateAddress;
    }

    /**
     * Sets the value of the reasonForThirdPartyOrAlternateAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReasonForThirdPartyOrAlternateAddress(JAXBElement<String> value) {
        this.reasonForThirdPartyOrAlternateAddress = value;
    }

    /**
     * Gets the value of the receiptRefID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReceiptRefID() {
        return receiptRefID;
    }

    /**
     * Sets the value of the receiptRefID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReceiptRefID(JAXBElement<String> value) {
        this.receiptRefID = value;
    }

    /**
     * Gets the value of the receiverBIC property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReceiverBIC() {
        return receiverBIC;
    }

    /**
     * Sets the value of the receiverBIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReceiverBIC(JAXBElement<String> value) {
        this.receiverBIC = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReferenceNumber(JAXBElement<String> value) {
        this.referenceNumber = value;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRequestType(JAXBElement<String> value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the specialInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSpecialInstructions() {
        return specialInstructions;
    }

    /**
     * Sets the value of the specialInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSpecialInstructions(JAXBElement<String> value) {
        this.specialInstructions = value;
    }

    /**
     * Gets the value of the thirdPartyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public JAXBElement<AccountAndAddress> getThirdPartyAddress() {
        return thirdPartyAddress;
    }

    /**
     * Sets the value of the thirdPartyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AccountAndAddress }{@code >}
     *     
     */
    public void setThirdPartyAddress(JAXBElement<AccountAndAddress> value) {
        this.thirdPartyAddress = value;
    }

    /**
     * Gets the value of the transactionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TransactionDetails }{@code >}
     *     
     */
    public JAXBElement<TransactionDetails> getTransactionDetails() {
        return transactionDetails;
    }

    /**
     * Sets the value of the transactionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TransactionDetails }{@code >}
     *     
     */
    public void setTransactionDetails(JAXBElement<TransactionDetails> value) {
        this.transactionDetails = value;
    }

    /**
     * Gets the value of the wireReference property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWireReference() {
        return wireReference;
    }

    /**
     * Sets the value of the wireReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWireReference(JAXBElement<String> value) {
        this.wireReference = value;
    }

}
