//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.12 at 08:59:07 AM IST 
//


package com.zabetan.behpardakht.ipg.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ira complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ira"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AdditionalIrsType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentContribution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentDistribution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentEmployeeContribution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentEmployerContribution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentPreDistribution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentYearContributionLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentYearEmployeeContributionLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentYearEmployerContributionLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DistributionAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExcessEarnings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExcessEarningsFederalWithHoldingAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExcessEarningsFederalWithHoldingAmountInPercentage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExcessEarningsStateWithHoldingAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExcessEarningsStateWithHoldingAmountInPercentage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExistingFederalWithHoldingAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExistingStateWithHoldingAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FederalMinimumPercentage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FederalWithHoldingAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FederalWithHoldingAmountInPercentage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="GLBranch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="GLDepartment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IRADisbursementType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IRATransactionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IRSType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastContribution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastDistribution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastEmployeeContribution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastEmployerContribution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastPreDistribution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NetDistributionAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NetExcessEarnings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OverrideCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PlanType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PriorYearContributionLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PriorYearEmployeeContributionLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PriorYearEmployerContributionLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RMDAccountingType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RMDAcctType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StateMinimumPercentage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StateWithHoldingAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StateWithHoldingAmountInPercentage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WithHoldChecked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="WithholdFederalTaxes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WithholdStateTaxes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ira", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", propOrder = {
    "additionalIrsType",
    "currentContribution",
    "currentDistribution",
    "currentEmployeeContribution",
    "currentEmployerContribution",
    "currentPreDistribution",
    "currentYearContributionLimit",
    "currentYearEmployeeContributionLimit",
    "currentYearEmployerContributionLimit",
    "dateOfBirth",
    "distributionAmount",
    "excessEarnings",
    "excessEarningsFederalWithHoldingAmount",
    "excessEarningsFederalWithHoldingAmountInPercentage",
    "excessEarningsStateWithHoldingAmount",
    "excessEarningsStateWithHoldingAmountInPercentage",
    "existingFederalWithHoldingAmount",
    "existingStateWithHoldingAmount",
    "federalMinimumPercentage",
    "federalWithHoldingAmount",
    "federalWithHoldingAmountInPercentage",
    "glBranch",
    "glDepartment",
    "iraDisbursementType",
    "iraTransactionType",
    "irsType",
    "lastContribution",
    "lastDistribution",
    "lastEmployeeContribution",
    "lastEmployerContribution",
    "lastPreDistribution",
    "netDistributionAmount",
    "netExcessEarnings",
    "overrideCode",
    "planType",
    "priorYearContributionLimit",
    "priorYearEmployeeContributionLimit",
    "priorYearEmployerContributionLimit",
    "rmdAccountingType",
    "rmdAcctType",
    "stateMinimumPercentage",
    "stateWithHoldingAmount",
    "stateWithHoldingAmountInPercentage",
    "withHoldChecked",
    "withholdFederalTaxes",
    "withholdStateTaxes",
    "year"
})
public class Ira {

    @XmlElementRef(name = "AdditionalIrsType", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> additionalIrsType;
    @XmlElementRef(name = "CurrentContribution", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currentContribution;
    @XmlElementRef(name = "CurrentDistribution", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currentDistribution;
    @XmlElementRef(name = "CurrentEmployeeContribution", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currentEmployeeContribution;
    @XmlElementRef(name = "CurrentEmployerContribution", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currentEmployerContribution;
    @XmlElementRef(name = "CurrentPreDistribution", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currentPreDistribution;
    @XmlElementRef(name = "CurrentYearContributionLimit", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currentYearContributionLimit;
    @XmlElementRef(name = "CurrentYearEmployeeContributionLimit", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currentYearEmployeeContributionLimit;
    @XmlElementRef(name = "CurrentYearEmployerContributionLimit", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currentYearEmployerContributionLimit;
    @XmlElementRef(name = "DateOfBirth", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dateOfBirth;
    @XmlElementRef(name = "DistributionAmount", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> distributionAmount;
    @XmlElementRef(name = "ExcessEarnings", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> excessEarnings;
    @XmlElementRef(name = "ExcessEarningsFederalWithHoldingAmount", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> excessEarningsFederalWithHoldingAmount;
    @XmlElementRef(name = "ExcessEarningsFederalWithHoldingAmountInPercentage", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> excessEarningsFederalWithHoldingAmountInPercentage;
    @XmlElementRef(name = "ExcessEarningsStateWithHoldingAmount", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> excessEarningsStateWithHoldingAmount;
    @XmlElementRef(name = "ExcessEarningsStateWithHoldingAmountInPercentage", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> excessEarningsStateWithHoldingAmountInPercentage;
    @XmlElementRef(name = "ExistingFederalWithHoldingAmount", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> existingFederalWithHoldingAmount;
    @XmlElementRef(name = "ExistingStateWithHoldingAmount", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> existingStateWithHoldingAmount;
    @XmlElementRef(name = "FederalMinimumPercentage", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> federalMinimumPercentage;
    @XmlElementRef(name = "FederalWithHoldingAmount", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> federalWithHoldingAmount;
    @XmlElementRef(name = "FederalWithHoldingAmountInPercentage", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> federalWithHoldingAmountInPercentage;
    @XmlElementRef(name = "GLBranch", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> glBranch;
    @XmlElementRef(name = "GLDepartment", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> glDepartment;
    @XmlElementRef(name = "IRADisbursementType", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> iraDisbursementType;
    @XmlElementRef(name = "IRATransactionType", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> iraTransactionType;
    @XmlElementRef(name = "IRSType", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> irsType;
    @XmlElementRef(name = "LastContribution", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lastContribution;
    @XmlElementRef(name = "LastDistribution", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lastDistribution;
    @XmlElementRef(name = "LastEmployeeContribution", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lastEmployeeContribution;
    @XmlElementRef(name = "LastEmployerContribution", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lastEmployerContribution;
    @XmlElementRef(name = "LastPreDistribution", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lastPreDistribution;
    @XmlElementRef(name = "NetDistributionAmount", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> netDistributionAmount;
    @XmlElementRef(name = "NetExcessEarnings", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> netExcessEarnings;
    @XmlElementRef(name = "OverrideCode", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> overrideCode;
    @XmlElementRef(name = "PlanType", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> planType;
    @XmlElementRef(name = "PriorYearContributionLimit", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> priorYearContributionLimit;
    @XmlElementRef(name = "PriorYearEmployeeContributionLimit", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> priorYearEmployeeContributionLimit;
    @XmlElementRef(name = "PriorYearEmployerContributionLimit", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> priorYearEmployerContributionLimit;
    @XmlElementRef(name = "RMDAccountingType", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> rmdAccountingType;
    @XmlElementRef(name = "RMDAcctType", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> rmdAcctType;
    @XmlElementRef(name = "StateMinimumPercentage", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> stateMinimumPercentage;
    @XmlElementRef(name = "StateWithHoldingAmount", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> stateWithHoldingAmount;
    @XmlElementRef(name = "StateWithHoldingAmountInPercentage", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> stateWithHoldingAmountInPercentage;
    @XmlElement(name = "WithHoldChecked")
    protected Boolean withHoldChecked;
    @XmlElementRef(name = "WithholdFederalTaxes", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> withholdFederalTaxes;
    @XmlElementRef(name = "WithholdStateTaxes", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> withholdStateTaxes;
    @XmlElementRef(name = "Year", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> year;

    /**
     * Gets the value of the additionalIrsType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAdditionalIrsType() {
        return additionalIrsType;
    }

    /**
     * Sets the value of the additionalIrsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAdditionalIrsType(JAXBElement<String> value) {
        this.additionalIrsType = value;
    }

    /**
     * Gets the value of the currentContribution property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrentContribution() {
        return currentContribution;
    }

    /**
     * Sets the value of the currentContribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrentContribution(JAXBElement<String> value) {
        this.currentContribution = value;
    }

    /**
     * Gets the value of the currentDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrentDistribution() {
        return currentDistribution;
    }

    /**
     * Sets the value of the currentDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrentDistribution(JAXBElement<String> value) {
        this.currentDistribution = value;
    }

    /**
     * Gets the value of the currentEmployeeContribution property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrentEmployeeContribution() {
        return currentEmployeeContribution;
    }

    /**
     * Sets the value of the currentEmployeeContribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrentEmployeeContribution(JAXBElement<String> value) {
        this.currentEmployeeContribution = value;
    }

    /**
     * Gets the value of the currentEmployerContribution property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrentEmployerContribution() {
        return currentEmployerContribution;
    }

    /**
     * Sets the value of the currentEmployerContribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrentEmployerContribution(JAXBElement<String> value) {
        this.currentEmployerContribution = value;
    }

    /**
     * Gets the value of the currentPreDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrentPreDistribution() {
        return currentPreDistribution;
    }

    /**
     * Sets the value of the currentPreDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrentPreDistribution(JAXBElement<String> value) {
        this.currentPreDistribution = value;
    }

    /**
     * Gets the value of the currentYearContributionLimit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrentYearContributionLimit() {
        return currentYearContributionLimit;
    }

    /**
     * Sets the value of the currentYearContributionLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrentYearContributionLimit(JAXBElement<String> value) {
        this.currentYearContributionLimit = value;
    }

    /**
     * Gets the value of the currentYearEmployeeContributionLimit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrentYearEmployeeContributionLimit() {
        return currentYearEmployeeContributionLimit;
    }

    /**
     * Sets the value of the currentYearEmployeeContributionLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrentYearEmployeeContributionLimit(JAXBElement<String> value) {
        this.currentYearEmployeeContributionLimit = value;
    }

    /**
     * Gets the value of the currentYearEmployerContributionLimit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrentYearEmployerContributionLimit() {
        return currentYearEmployerContributionLimit;
    }

    /**
     * Sets the value of the currentYearEmployerContributionLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrentYearEmployerContributionLimit(JAXBElement<String> value) {
        this.currentYearEmployerContributionLimit = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDateOfBirth(JAXBElement<String> value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the distributionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDistributionAmount() {
        return distributionAmount;
    }

    /**
     * Sets the value of the distributionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDistributionAmount(JAXBElement<String> value) {
        this.distributionAmount = value;
    }

    /**
     * Gets the value of the excessEarnings property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExcessEarnings() {
        return excessEarnings;
    }

    /**
     * Sets the value of the excessEarnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExcessEarnings(JAXBElement<String> value) {
        this.excessEarnings = value;
    }

    /**
     * Gets the value of the excessEarningsFederalWithHoldingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExcessEarningsFederalWithHoldingAmount() {
        return excessEarningsFederalWithHoldingAmount;
    }

    /**
     * Sets the value of the excessEarningsFederalWithHoldingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExcessEarningsFederalWithHoldingAmount(JAXBElement<String> value) {
        this.excessEarningsFederalWithHoldingAmount = value;
    }

    /**
     * Gets the value of the excessEarningsFederalWithHoldingAmountInPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExcessEarningsFederalWithHoldingAmountInPercentage() {
        return excessEarningsFederalWithHoldingAmountInPercentage;
    }

    /**
     * Sets the value of the excessEarningsFederalWithHoldingAmountInPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExcessEarningsFederalWithHoldingAmountInPercentage(JAXBElement<String> value) {
        this.excessEarningsFederalWithHoldingAmountInPercentage = value;
    }

    /**
     * Gets the value of the excessEarningsStateWithHoldingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExcessEarningsStateWithHoldingAmount() {
        return excessEarningsStateWithHoldingAmount;
    }

    /**
     * Sets the value of the excessEarningsStateWithHoldingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExcessEarningsStateWithHoldingAmount(JAXBElement<String> value) {
        this.excessEarningsStateWithHoldingAmount = value;
    }

    /**
     * Gets the value of the excessEarningsStateWithHoldingAmountInPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExcessEarningsStateWithHoldingAmountInPercentage() {
        return excessEarningsStateWithHoldingAmountInPercentage;
    }

    /**
     * Sets the value of the excessEarningsStateWithHoldingAmountInPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExcessEarningsStateWithHoldingAmountInPercentage(JAXBElement<String> value) {
        this.excessEarningsStateWithHoldingAmountInPercentage = value;
    }

    /**
     * Gets the value of the existingFederalWithHoldingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExistingFederalWithHoldingAmount() {
        return existingFederalWithHoldingAmount;
    }

    /**
     * Sets the value of the existingFederalWithHoldingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExistingFederalWithHoldingAmount(JAXBElement<String> value) {
        this.existingFederalWithHoldingAmount = value;
    }

    /**
     * Gets the value of the existingStateWithHoldingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExistingStateWithHoldingAmount() {
        return existingStateWithHoldingAmount;
    }

    /**
     * Sets the value of the existingStateWithHoldingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExistingStateWithHoldingAmount(JAXBElement<String> value) {
        this.existingStateWithHoldingAmount = value;
    }

    /**
     * Gets the value of the federalMinimumPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFederalMinimumPercentage() {
        return federalMinimumPercentage;
    }

    /**
     * Sets the value of the federalMinimumPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFederalMinimumPercentage(JAXBElement<String> value) {
        this.federalMinimumPercentage = value;
    }

    /**
     * Gets the value of the federalWithHoldingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFederalWithHoldingAmount() {
        return federalWithHoldingAmount;
    }

    /**
     * Sets the value of the federalWithHoldingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFederalWithHoldingAmount(JAXBElement<String> value) {
        this.federalWithHoldingAmount = value;
    }

    /**
     * Gets the value of the federalWithHoldingAmountInPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFederalWithHoldingAmountInPercentage() {
        return federalWithHoldingAmountInPercentage;
    }

    /**
     * Sets the value of the federalWithHoldingAmountInPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFederalWithHoldingAmountInPercentage(JAXBElement<String> value) {
        this.federalWithHoldingAmountInPercentage = value;
    }

    /**
     * Gets the value of the glBranch property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getGLBranch() {
        return glBranch;
    }

    /**
     * Sets the value of the glBranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setGLBranch(JAXBElement<String> value) {
        this.glBranch = value;
    }

    /**
     * Gets the value of the glDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getGLDepartment() {
        return glDepartment;
    }

    /**
     * Sets the value of the glDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setGLDepartment(JAXBElement<String> value) {
        this.glDepartment = value;
    }

    /**
     * Gets the value of the iraDisbursementType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIRADisbursementType() {
        return iraDisbursementType;
    }

    /**
     * Sets the value of the iraDisbursementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIRADisbursementType(JAXBElement<String> value) {
        this.iraDisbursementType = value;
    }

    /**
     * Gets the value of the iraTransactionType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIRATransactionType() {
        return iraTransactionType;
    }

    /**
     * Sets the value of the iraTransactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIRATransactionType(JAXBElement<String> value) {
        this.iraTransactionType = value;
    }

    /**
     * Gets the value of the irsType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIRSType() {
        return irsType;
    }

    /**
     * Sets the value of the irsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIRSType(JAXBElement<String> value) {
        this.irsType = value;
    }

    /**
     * Gets the value of the lastContribution property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLastContribution() {
        return lastContribution;
    }

    /**
     * Sets the value of the lastContribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLastContribution(JAXBElement<String> value) {
        this.lastContribution = value;
    }

    /**
     * Gets the value of the lastDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLastDistribution() {
        return lastDistribution;
    }

    /**
     * Sets the value of the lastDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLastDistribution(JAXBElement<String> value) {
        this.lastDistribution = value;
    }

    /**
     * Gets the value of the lastEmployeeContribution property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLastEmployeeContribution() {
        return lastEmployeeContribution;
    }

    /**
     * Sets the value of the lastEmployeeContribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLastEmployeeContribution(JAXBElement<String> value) {
        this.lastEmployeeContribution = value;
    }

    /**
     * Gets the value of the lastEmployerContribution property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLastEmployerContribution() {
        return lastEmployerContribution;
    }

    /**
     * Sets the value of the lastEmployerContribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLastEmployerContribution(JAXBElement<String> value) {
        this.lastEmployerContribution = value;
    }

    /**
     * Gets the value of the lastPreDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLastPreDistribution() {
        return lastPreDistribution;
    }

    /**
     * Sets the value of the lastPreDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLastPreDistribution(JAXBElement<String> value) {
        this.lastPreDistribution = value;
    }

    /**
     * Gets the value of the netDistributionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNetDistributionAmount() {
        return netDistributionAmount;
    }

    /**
     * Sets the value of the netDistributionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNetDistributionAmount(JAXBElement<String> value) {
        this.netDistributionAmount = value;
    }

    /**
     * Gets the value of the netExcessEarnings property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNetExcessEarnings() {
        return netExcessEarnings;
    }

    /**
     * Sets the value of the netExcessEarnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNetExcessEarnings(JAXBElement<String> value) {
        this.netExcessEarnings = value;
    }

    /**
     * Gets the value of the overrideCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOverrideCode() {
        return overrideCode;
    }

    /**
     * Sets the value of the overrideCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOverrideCode(JAXBElement<String> value) {
        this.overrideCode = value;
    }

    /**
     * Gets the value of the planType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPlanType() {
        return planType;
    }

    /**
     * Sets the value of the planType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPlanType(JAXBElement<String> value) {
        this.planType = value;
    }

    /**
     * Gets the value of the priorYearContributionLimit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPriorYearContributionLimit() {
        return priorYearContributionLimit;
    }

    /**
     * Sets the value of the priorYearContributionLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPriorYearContributionLimit(JAXBElement<String> value) {
        this.priorYearContributionLimit = value;
    }

    /**
     * Gets the value of the priorYearEmployeeContributionLimit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPriorYearEmployeeContributionLimit() {
        return priorYearEmployeeContributionLimit;
    }

    /**
     * Sets the value of the priorYearEmployeeContributionLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPriorYearEmployeeContributionLimit(JAXBElement<String> value) {
        this.priorYearEmployeeContributionLimit = value;
    }

    /**
     * Gets the value of the priorYearEmployerContributionLimit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPriorYearEmployerContributionLimit() {
        return priorYearEmployerContributionLimit;
    }

    /**
     * Sets the value of the priorYearEmployerContributionLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPriorYearEmployerContributionLimit(JAXBElement<String> value) {
        this.priorYearEmployerContributionLimit = value;
    }

    /**
     * Gets the value of the rmdAccountingType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRMDAccountingType() {
        return rmdAccountingType;
    }

    /**
     * Sets the value of the rmdAccountingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRMDAccountingType(JAXBElement<String> value) {
        this.rmdAccountingType = value;
    }

    /**
     * Gets the value of the rmdAcctType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRMDAcctType() {
        return rmdAcctType;
    }

    /**
     * Sets the value of the rmdAcctType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRMDAcctType(JAXBElement<String> value) {
        this.rmdAcctType = value;
    }

    /**
     * Gets the value of the stateMinimumPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStateMinimumPercentage() {
        return stateMinimumPercentage;
    }

    /**
     * Sets the value of the stateMinimumPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStateMinimumPercentage(JAXBElement<String> value) {
        this.stateMinimumPercentage = value;
    }

    /**
     * Gets the value of the stateWithHoldingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStateWithHoldingAmount() {
        return stateWithHoldingAmount;
    }

    /**
     * Sets the value of the stateWithHoldingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStateWithHoldingAmount(JAXBElement<String> value) {
        this.stateWithHoldingAmount = value;
    }

    /**
     * Gets the value of the stateWithHoldingAmountInPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStateWithHoldingAmountInPercentage() {
        return stateWithHoldingAmountInPercentage;
    }

    /**
     * Sets the value of the stateWithHoldingAmountInPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStateWithHoldingAmountInPercentage(JAXBElement<String> value) {
        this.stateWithHoldingAmountInPercentage = value;
    }

    /**
     * Gets the value of the withHoldChecked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWithHoldChecked() {
        return withHoldChecked;
    }

    /**
     * Sets the value of the withHoldChecked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWithHoldChecked(Boolean value) {
        this.withHoldChecked = value;
    }

    /**
     * Gets the value of the withholdFederalTaxes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWithholdFederalTaxes() {
        return withholdFederalTaxes;
    }

    /**
     * Sets the value of the withholdFederalTaxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWithholdFederalTaxes(JAXBElement<String> value) {
        this.withholdFederalTaxes = value;
    }

    /**
     * Gets the value of the withholdStateTaxes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWithholdStateTaxes() {
        return withholdStateTaxes;
    }

    /**
     * Sets the value of the withholdStateTaxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWithholdStateTaxes(JAXBElement<String> value) {
        this.withholdStateTaxes = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setYear(JAXBElement<String> value) {
        this.year = value;
    }

}
