//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.12 at 08:59:07 AM IST 
//


package com.zabetan.behpardakht.ipg.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Request"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AchInstructions" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}ArrayOfAchInstruction" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalAccountProfiles" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}ArrayOfAdditionalAccountInfo" minOccurs="0"/&gt;
 *         &lt;element name="AdvisoryData" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Core.Backend.Application.Contracts.DTO}AdvisoryData" minOccurs="0"/&gt;
 *         &lt;element name="CdmAdminData" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}CdmAdminData" minOccurs="0"/&gt;
 *         &lt;element name="Disbursement" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}Disbursement" minOccurs="0"/&gt;
 *         &lt;element name="PaymentSummaries" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}ArrayOfPaymentSummary" minOccurs="0"/&gt;
 *         &lt;element name="RequestType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Requestor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WireInstructions" type="{http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts}ArrayOfWireRecurringInstructionMini" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Request", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", propOrder = {
    "achInstructions",
    "additionalAccountProfiles",
    "advisoryData",
    "cdmAdminData",
    "disbursement",
    "paymentSummaries",
    "requestType",
    "requestor",
    "wireInstructions"
})
public class Request {

    @XmlElementRef(name = "AchInstructions", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAchInstruction> achInstructions;
    @XmlElementRef(name = "AdditionalAccountProfiles", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAdditionalAccountInfo> additionalAccountProfiles;
    @XmlElementRef(name = "AdvisoryData", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<AdvisoryData> advisoryData;
    @XmlElementRef(name = "CdmAdminData", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<CdmAdminData> cdmAdminData;
    @XmlElementRef(name = "Disbursement", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<Disbursement> disbursement;
    @XmlElementRef(name = "PaymentSummaries", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfPaymentSummary> paymentSummaries;
    @XmlElementRef(name = "RequestType", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> requestType;
    @XmlElementRef(name = "Requestor", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<String> requestor;
    @XmlElementRef(name = "WireInstructions", namespace = "http://schemas.datacontract.org/2004/07/SunGard.Phase3.Cdm.Backend.Service.Contracts", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfWireRecurringInstructionMini> wireInstructions;

    /**
     * Gets the value of the achInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAchInstruction }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAchInstruction> getAchInstructions() {
        return achInstructions;
    }

    /**
     * Sets the value of the achInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAchInstruction }{@code >}
     *     
     */
    public void setAchInstructions(JAXBElement<ArrayOfAchInstruction> value) {
        this.achInstructions = value;
    }

    /**
     * Gets the value of the additionalAccountProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAdditionalAccountInfo }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAdditionalAccountInfo> getAdditionalAccountProfiles() {
        return additionalAccountProfiles;
    }

    /**
     * Sets the value of the additionalAccountProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAdditionalAccountInfo }{@code >}
     *     
     */
    public void setAdditionalAccountProfiles(JAXBElement<ArrayOfAdditionalAccountInfo> value) {
        this.additionalAccountProfiles = value;
    }

    /**
     * Gets the value of the advisoryData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AdvisoryData }{@code >}
     *     
     */
    public JAXBElement<AdvisoryData> getAdvisoryData() {
        return advisoryData;
    }

    /**
     * Sets the value of the advisoryData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AdvisoryData }{@code >}
     *     
     */
    public void setAdvisoryData(JAXBElement<AdvisoryData> value) {
        this.advisoryData = value;
    }

    /**
     * Gets the value of the cdmAdminData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CdmAdminData }{@code >}
     *     
     */
    public JAXBElement<CdmAdminData> getCdmAdminData() {
        return cdmAdminData;
    }

    /**
     * Sets the value of the cdmAdminData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CdmAdminData }{@code >}
     *     
     */
    public void setCdmAdminData(JAXBElement<CdmAdminData> value) {
        this.cdmAdminData = value;
    }

    /**
     * Gets the value of the disbursement property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Disbursement }{@code >}
     *     
     */
    public JAXBElement<Disbursement> getDisbursement() {
        return disbursement;
    }

    /**
     * Sets the value of the disbursement property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Disbursement }{@code >}
     *     
     */
    public void setDisbursement(JAXBElement<Disbursement> value) {
        this.disbursement = value;
    }

    /**
     * Gets the value of the paymentSummaries property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfPaymentSummary }{@code >}
     *     
     */
    public JAXBElement<ArrayOfPaymentSummary> getPaymentSummaries() {
        return paymentSummaries;
    }

    /**
     * Sets the value of the paymentSummaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfPaymentSummary }{@code >}
     *     
     */
    public void setPaymentSummaries(JAXBElement<ArrayOfPaymentSummary> value) {
        this.paymentSummaries = value;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRequestType(JAXBElement<String> value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the requestor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRequestor() {
        return requestor;
    }

    /**
     * Sets the value of the requestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRequestor(JAXBElement<String> value) {
        this.requestor = value;
    }

    /**
     * Gets the value of the wireInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfWireRecurringInstructionMini }{@code >}
     *     
     */
    public JAXBElement<ArrayOfWireRecurringInstructionMini> getWireInstructions() {
        return wireInstructions;
    }

    /**
     * Sets the value of the wireInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfWireRecurringInstructionMini }{@code >}
     *     
     */
    public void setWireInstructions(JAXBElement<ArrayOfWireRecurringInstructionMini> value) {
        this.wireInstructions = value;
    }

}
